version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./backend
    container_name: backend
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Parth5413p
      POSTGRES_DB: clarisma
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5435:5432"

volumes:
  postgres_data:
