version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    restart: always

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - backend-audio
      - backend-video
    restart: always

  backend-audio:
    build:
      context: ./backend-audio
    container_name: backend-audio
    ports:
      - "8002:8002"
    restart: always

  backend-video:
    build:
      context: ./backend-video
    container_name: backend-video
    ports:
      - "8003:8003"
    restart: always
